{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.hpa.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.hpa.targetDeployment }}"
  minReplicas: "{{ .Values.autoscaling.minReplicas }}"
  maxReplicas: "{{ .Values.autoscaling.maxReplicas }}"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: "{{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}"
      policies:
        - type: Pods
          value: "{{ .Values.autoscaling.scaleDown.pods }}"
          periodSeconds: "{{ .Values.autoscaling.scaleDown.periodSeconds }}"
    scaleUp:
      stabilizationWindowSeconds: "{{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}"
      policies:
        - type: Pods
          value: "{{ .Values.autoscaling.scaleUp.pods }}"
          periodSeconds: "{{ .Values.autoscaling.scaleUp.periodSeconds }}"
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: "{{ .Values.autoscaling.targetCPUUtilizationPercentage }}"
{{- end }}