---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.imagePullSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.dockerRegistrySecret }}
  template:
    metadata:
      name: {{ .Values.imagePullSecretName }}
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson
