deployment:
  name: attendance-app
  containerPort: 5000

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

label: attendance-app

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: gauris17/attendanceapp
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

imagePullSecretName: docker-creds

dockerRegistrySecret: AgCYQaSuSO2Hq6jjHk5k6kQm3n3/8kjhTM4WVnUP2qmW+AzPmhC5l48xcqo3Fr5ps3XcdGgq7IveMgRADdayq6EWd+B/6+E7YIuaYAD7Z1ahDb/wR70nOyjfX79U9xQhfPoiz+tKMvxL/WtxDbF0FvtD9Qk3QlBxLNk2CMTff3KMfYL/0+z2AK6T6plndi3Kxtq8pn7aeEkOij+yQMOpMNg/jJcT6TonT6ZH5xUd9jfSH12V5hJM2v817FDL7V4SYmSaBbwrMjQttDMCvn+AzzA1pMpZZKIflp2jC35VIF069dWFz2ebosa0lfqfHnX5xcnhej2iMRn+sHsxZbF3N06Qi/IJsBGgJiSVA8licziS9+1JpsXDv+Z/Qcg7Wq1mmdMJx4dstPuJfqm7wqz1YuqOZuc6zaYVguEH9Ja2JVsdfKZZZWMv9LocDkPezygk1AD3cwFUf3gQFlUEpTWHOD/2L2o7FA2coiC03E83Z6XssOWtxAG48iBwy0BYwBDRC8i3RKiJbfR+HNlWpYUYN/V7JPT3RxI7PV34arPmZjGcEuxlkNd/eSDmE58NDY2NCOwDYm2KQCTl33gPRYz0GBMZWkWl416drr+pAxO+IqXkS/HYAnYvIAPx5MSiJtSeAkPgiMukT19MdrRdjPznvDXCIGKCwHj3dVEXXDSJ5FYbfMv/VgeeUWW6DD8SaGCXKPiF5yAZSvPnXbhpqSGzf3qFxkHEogB/t3N0vPQ+tndz7rHNl9hMXGApBD6528IpCR7C6J2R3LstHW0g4YekxsABUlu50RFQpjBBH5dhJcVST4ShFUhA6yil2swCPki9S/TFzOShzktFgF5MKC5SpsNB2Cktonys/j5tow==

# Project namespace for your application
namespace: attendance-app

dbSecretName: db-secrets

dbUser: AgBgfPwt2pV5CQCJHkvOSmZVo6o1pjxuKpXTx0YH8ZQhbAQ8oN6TRAmYkOsRWoKF/pIZ0rfIbVRFdSINwP9UKVNBxRFfvoWea71TiH62BLsU+JIXwcBvER/s37ywf266211dZt+9TdFq1++E8FeqMa86a8p377TKv63TemEgF2HSk+u5H6KcTnKSTsLq6UAumio30XM9wyELzhtey348kfpBRssxDSs0GGUhdVHAuTMp80lHuxYEkB52FaTVR+YiQ/O5HtVOkA9DOoakTUqFQ8b6Cwz1oYJ3DptK9Cy8HdcxwdLqOuXIKeRpFgZELc6rmhku6YMfZvvFCcFTVjO+4LWNW2A8IfRl/wsnfq1SnDNLrziYSFca1Ia2LW+TqQpQ6RNc6xJiZlIYhE3aAg+JPs3n0q9B2XIGmMqOYLG5bKAR7w9x1V4fC3MoirZwFqgMxsdbJCR3BxRZGMRVAUTj+MLKHAK/oySWRjo5G27UrFNyQpGYXgEHwb5tY8sZDe8CqwaABxXUNhASavkfcrpjOS9Jviiefg4LVSjfiko5XcFxzGzcL2Tr+/q2J6+RSzl7IFmdB2VwzqovrRVnAk+jKjZDwq9afM32aNrszBPSHLDuEfBbeaG2gxhRRSbtPnMjQxynLGasWc/hS66uP3bUvtQ9Gc8HcH7Grv4SkDaj5QK9+RnMVmfuRwtjP/FKW9QzkeVR8AREJu9dMw==
dbPassword: AgDC9WayLfstmPdVwhU+V6gVelkXTgaypKNGd7dpy5SIc1/GmoVRJ0Sn8kNja1YJa/M/vEbj5xk6RR+mjAjPlnW2Xi3JKKcB43M4Xf8d8tENOzw9jy83njL2QjGSzBohI53mHxpcqaumWrtsTMtMSgU5y60kTQJOaU5LXHnSYW1N+xJR1CVNbDpgwwC5Hla6+6KLW6oZXxONeWMR54Wiq1EPEyB7shXDNmWY4WhcSREOPmbq0gJGY+fgfWBGClxH9JIZ5kB4HRXLAfU5mmKp3AgLuZhm90rDWFAEZoEzpyoLO7ZVIHkZlvFXJUfXEsbjrWOlYZfvGawXNvajKfJfX6C8tmiUMcGMKjBeTfX4F6YJP7AyOazn0kK/tfjt1Paz72R9AhFXdxjnBRSydhB7GV8wyblbt6qOTdxV+kVWT8vaoyxDXJUHRbmKL2MXzj6exnoA3I1TLLhvTM7PGISnVMven3ZqLkO48ZpbwD1SKC+g74/cznHb4WX7X2LoSqUVBDQtz9AYgcbBefsKDdOrU3R9Y8J81uPgjC01zODVnojHrg+0HIj5kMbKNKXYo5zC9aZRRYIUIfBd0R1QgV3OBuoU6t5pxC1krQQA9Em2pH4pst8EFc/YhFYGz08ap+GonbjZsgKLVUKZU6QVNXAhAIor1js0QWgDZ/j3MPKdEx4FmN4OZDlapgDhHP+4Nx1YxO7gnl2pl4LMow==

config:
  name: web-config
  DB_HOST: database-1.cluster-cjo2qwqge1cu.ap-south-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: attendance-app-service
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: LoadBalancer
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

  scaleDown:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

  scaleUp:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

hpa:
  name: attendance-app-hpa
  targetDeployment: attendance-app


